title: bogeorge.github.io
email: your-email@example.com
description: >-  
  Personal site powered by Jekyll and GitHub Pages
baseurl: ""
url: "https://bogeorge.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
github:
  is_project_page: true
